# Install after issuing the certificate with Certbot's Nginx plugin.
server {
    listen 80;
    server_name pokeshop-app.duckdns.org 62.171.169.187;
    return 301 https://pokeshop-app.duckdns.org$request_uri;
}

server {
    listen 443 ssl;
    server_name pokeshop-app.duckdns.org;
    ssl_certificate /etc/letsencrypt/live/pokeshop-app.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pokeshop-app.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    client_max_body_size 1m;
    location / {
        proxy_pass http://127.0.0.1:8091;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
